# -*- coding: utf-8 -*-
"""Session_5_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fby26zKl0JMkqmEtmsc9pDE2VCe2XGY9
"""

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/ecommerce_customer_dataset.csv")

print("Missing Values Count:\n", df.isnull().sum())

# df.head(60)

# Option 1: Remove rows with missing values
df_dropped = df.dropna()
print("\nData after dropping missing values:\n", df_dropped)

# Option 2: Fill missing values
df_filled = df.copy()
df_filled['Age'].fillna(df_filled['Age'].mean(), inplace=True)  # Fill numerical with mean
df_filled['Annual_Income'].fillna(df_filled['Annual_Income'].mode()[0], inplace=True)  # Fill categorical with mode
df_filled['Spending_Score'].fillna(df_filled['Spending_Score'].median(), inplace=True)  # Fill numerical with median
df_filled['Preferred_Category'].fillna(df_filled['Preferred_Category'].mode()[0], inplace=True)  # Fill categorical with mode

print("\nData after filling missing values:\n", df_filled)

# Drop duplicate entries
df_no_duplicates = df_filled.drop_duplicates()
print("\nData after dropping duplicates:\n", df_no_duplicates)

#  Normalize Annual_Income & Spending_Score using Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_no_duplicates[['Annual_Income', 'Spending_Score']] = scaler.fit_transform(df_no_duplicates[['Annual_Income', 'Spending_Score']])
print("\nData after normalization:\n", df_no_duplicates)

# Standardize Purchase_Frequency using Z-score Normalization
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_no_duplicates[['Purchase_Frequency']] = scaler.fit_transform(df_no_duplicates[['Purchase_Frequency']])
print("\nData after standardization:\n", df_no_duplicates)

# Convert Gender into numerical values using One-Hot Encoding
df_no_duplicates= pd.get_dummies(df_no_duplicates, columns=['Gender'], drop_first=True)  # 'drop_first=True' avoids dummy variable trap
print("\nData after one-hot encoding:\n", df_no_duplicates)

# Label encode the Preferred_Category column
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df_no_duplicates['Preferred_Category'] = label_encoder.fit_transform(df_no_duplicates['Preferred_Category'])
print("\nData after label encoding:\n", df_no_duplicates)

def calculate_loyalty(Spending,Purchase):
  if Spending > 0.8 and Purchase > 0.2:
    return 'High'
  elif Spending < 0.8 and Purchase < 0.2:
    return 'Medium'
  else:
    return 'Low'

df_no_duplicates['Loyalty_Score']=df_no_duplicates.apply(lambda x: calculate_loyalty(x['Spending_Score'],x['Purchase_Frequency']),axis=1)
print(df_no_duplicates)

df_no_duplicates['Income_Level']=pd.cut(df_no_duplicates['Annual_Income'],bins=[0,0.3,0.6,0.8,1],labels=['Low','Medium','High','Very High'])
print(df_no_duplicates)

def engagement_category(Days,Purchase):
  if Days >=150 and Purchase > 0.2:
    return 'Active'
  elif Days <150 and Purchase < 0.2:
    return 'Dormant'
  else:
    return 'Churned'

df_no_duplicates['Engagement_Category'] = df_no_duplicates.apply(lambda x: engagement_category(x['Last_Transaction_Days'], x['Purchase_Frequency']), axis=1)
print(df_no_duplicates)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(df_no_duplicates['Age'], bins=20,color='aqua', edgecolor='blue')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Distribution of Age')
plt.show()

import seaborn as sns

plt.figure(figsize=(6,4))
sns.boxplot([df_no_duplicates['Annual_Income'], df_no_duplicates['Spending_Score']])
plt.ylabel('Annual_Income & Spending_Score')
plt.title('Boxplot of Annual_Income & Spending_Score')
plt.show()

# Preferred Category Count Visualization
plt.figure(figsize=(6,4))
sns.countplot(x='Preferred_Category', data=df_no_duplicates)
plt.xlabel('Preferred Category')
plt.ylabel('Count')
plt.title('Preferred Category Count')
plt.show()

# Income vs Spending Score Scatter Plot
plt.figure(figsize=(6,4))
sns.scatterplot(x='Annual_Income', y='Spending_Score', data=df_no_duplicates)
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.title('Income vs Spending Score')
plt.show()

# Gender vs Spending Score Box Plot
plt.figure(figsize=(8, 6))
sns.boxplot(x='Gender_Male', y='Spending_Score', data=df_no_duplicates)
plt.xlabel('Gender')
plt.ylabel('Spending Score')
plt.title('Gender vs Spending Score')
plt.xticks([0, 1], ['Female', 'Male'])  # Assuming 0 represents Female and 1 represents Male after one-hot encoding
plt.show()

plt.figure(figsize=(6,4))  # Adjust figure size as needed
sns.countplot(x='Preferred_Category', data=df_no_duplicates)
plt.xlabel('Preferred Category', fontsize=8)
plt.ylabel('Count', fontsize=8)
plt.title('Preferred Category Count', fontsize=8)
plt.show()

# Income vs Spending Score Scatter Plot
plt.figure(figsize=(8, 6))  # Adjust figure size as needed
sns.scatterplot(x='Annual_Income', y='Spending_Score', data=df_no_duplicates, hue='Loyalty_Score')
plt.xlabel('Annual Income', fontsize=12)
plt.ylabel('Spending Score', fontsize=12)
plt.title('Income vs Spending Score with Loyalty Score', fontsize=14)
plt.show()

# Gender vs Spending Score Box Plot
plt.figure(figsize=(8, 6))
sns.boxplot(x='Gender_Male', y='Spending_Score', data=df_no_duplicates)
plt.xlabel('Gender')
plt.ylabel('Spending Score')
plt.title('Gender vs Spending Score')
plt.xticks([0, 1], ['Female', 'Male'])  # Assuming 0 represents Female and 1 represents Male after one-hot encoding
plt.show()

# Correlation Heatmap
plt.figure(figsize=(6,4))
numeric_features = df_no_duplicates.select_dtypes(include=["number"])

corr_matrix = numeric_features.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".1f")
plt.title('Correlation Heatmap')
plt.show()

# Pair Plot
sns.pairplot(df_no_duplicates[['Annual_Income', 'Spending_Score', 'Purchase_Frequency', 'Age','Loyalty_Score']], hue='Loyalty_Score')
plt.show()

# Loyalty Score Distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Loyalty_Score', data=df_no_duplicates)
plt.xlabel('Loyalty Score')
plt.ylabel('Count')
plt.title('Loyalty Score Distribution')
plt.show()

# Loyalty Score Distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Loyalty_Score', data=df_no_duplicates)
plt.xlabel('Loyalty Score', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.title('Loyalty Score Distribution', fontsize=14)
plt.show()

# prompt: Create an Interactive Scatter Plot of Annual Income vs Spending Score
# Color customers based on their Loyalty Score (High, Medium, Low)
# Use hover effects to display customer details
# Enhance visualization interactivity using Plotly Express

import plotly.express as px

# Create the scatter plot using Plotly Express
fig = px.scatter(
    df_no_duplicates,
    x="Annual_Income",
    y="Spending_Score",
    color="Loyalty_Score",
    hover_data=["Customer_ID", "Age", "Preferred_Category"],  # Display customer details on hover
    title="Annual Income vs Spending Score with Loyalty Score"
)

# Customize the plot (optional)
fig.update_layout(
    xaxis_title="Annual Income",
    yaxis_title="Spending Score",
    font=dict(size=12)
)

# Show the interactive plot
fig.show()